"""Regenera reporte y presentacion ampliados para el cierre documental de Parte 2."""
from importlib import import_module
import json, subprocess
import pandas as pd
comun=import_module("200_parte2_comun"); O=comun.OUT/"14_segunda_pasada"; D=comun.DOCS
def esc(x):
 s=str(x); return s.replace('\\',r'\textbackslash{}').replace('&',r'\&').replace('%',r'\%').replace('_',r'\_\allowbreak{}').replace('#',r'\#')
def tab(df,cols,heads=None,fmt=None):
 rows=[]
 for _,r in df.iterrows():
  vals=[]
  for c in cols:
   v=r[c]; vals.append(esc(fmt[c](v) if fmt and c in fmt else ("--" if pd.isna(v) else v)))
  rows.append(" & ".join(vals)+r" \\")
 h=heads or cols
 width=max(.85,15.2/len(cols)); spec="".join([f">{{\\raggedright\\arraybackslash}}p{{{width:.2f}cm}}" for _ in cols])
 return r"{\scriptsize\setlength{\tabcolsep}{2pt}\begin{longtable}{"+spec+r"}\toprule "+" & ".join(map(esc,h))+r"\\\midrule\endhead "+"\n".join(rows)+r"\bottomrule\end{longtable}}"
def img(n,w='.94\\textwidth'): return rf"\begin{{figure}}[H]\centering\includegraphics[width={w}]{{{n}.png}}\end{{figure}}"
def main():
 sel=pd.read_csv(comun.OUT/"05_seleccion/seleccion_escenarios.csv"); p=sel[sel.rol.eq("PRINCIPAL")].iloc[0]
 ari=pd.read_csv(O/"resumen_ari_variantes.csv"); comp=pd.read_csv(O/"componentes_estabilidad_por_cluster.csv"); sub=pd.read_csv(O/"subnucleos_mega_cluster_documentados.csv")
 prof=pd.read_csv(comun.OUT/"07_perfiles/perfiles_clusters.csv"); prof=prof[prof.cluster.ge(0)].sort_values("pct__actividad_lavanderia_tintoreria",ascending=False)
 sens=pd.read_csv(comun.OUT/"11_cierre/sensibilidad_coexistencia.csv"); pairs=pd.read_csv(O/"explicacion_pares_similares.csv").head(10); top=pd.read_csv(O/"top_rasgos_por_cluster.csv")
 dic=pd.read_csv(O/"diccionario_variables_analiticas.csv"); allcfg=sel[["escenario_id","metodo","n_clusters","pct_ruido","pct_cluster_mayor","ari_top5_mismo_metodo","ari_perturbacion_25m"]]
 ari_t=tab(ari,["tipo_comparacion","n_comparaciones","ari_global_media","ari_sin_ruido_media","ari_sin_mega_media"],["Comparación","n","ARI global","ARI sin ruido","ARI sin mega"],{c:lambda x:f"{x:.3f}" for c in ["ari_global_media","ari_sin_ruido_media","ari_sin_mega_media"]})
 comp_t=tab(comp,["cluster_principal","n","estabilidad_media","jaccard_media","jaccard_min","pct_nucleo_robusto","pct_estable","pct_sensible"],["Cl.","n","Estab.","Jacc. med.","Jacc. mín.","Robusto %","Estable %","Sensible %"],{c:lambda x:f"{x:.2f}" for c in ["estabilidad_media","jaccard_media","jaccard_min","pct_nucleo_robusto","pct_estable","pct_sensible"]})
 sub_t=tab(sub,["subnucleo_id","n","pct_mega_cluster","municipio_dominante","localidad_dominante","area_convexa_km2","densidad_por_km2","n_localidades","distancia_mas_proximo_m"],["ID","n","% mega","Municipio","Localidad","Área km2","Dens./km2","Loc.","Vecino m"],{c:lambda x:f"{x:.1f}" for c in ["pct_mega_cluster","area_convexa_km2","densidad_por_km2","distancia_mas_proximo_m"]})
 subp_t=tab(sub,["subnucleo_id","pct__scian_textil","pct__actividad_lavanderia_tintoreria","pct__actividad_confeccion","pct__actividad_acabado_textil","pct__actividad_fabricacion_telas","pct__maquila","pct__senal_mezclilla_o_pantalon","pct__humedo_explicito","pct__proceso_seco_explicito","scian3_principales"],["ID","Man.","Lav.","Conf.","Acab.","Telas","Maq.","Mez./pant.","Húm.","Seco","SCIAN-3"],{c:lambda x:f"{x:.1f}" for c in sub.columns if c.startswith("pct__")})
 vars18=["cluster","n_dentro_cuenca","municipio_principal","localidad_principal","pct__actividad_lavanderia_tintoreria","pct__scian_textil","pct__actividad_confeccion","pct__actividad_acabado_textil","pct__maquila","pct__humedo_explicito","pct__proceso_seco_explicito","pct__senal_mezclilla_o_pantalon"]
 prof_t=tab(prof,vars18,["Cl.","n","Municipio","Localidad","Lav.","Man.","Conf.","Acab.","Maq.","Húm.","Seco","Mez./pant."],{c:lambda x:f"{x:.1f}" for c in vars18 if c.startswith("pct__")})
 pair_t=tab(pairs,["cluster_a","cluster_b","distancia_coseno","distancia_js","distancia_combinada","senales_compartidas","scian3_compartidos","diferencias_principales"],["A","B","Cos.","JS","Comb.","Señales compartidas","SCIAN compartidos","Diferencias"],{c:lambda x:f"{x:.3f}" for c in ["distancia_coseno","distancia_js","distancia_combinada"]})
 sens_t=tab(sens,list(sens.columns),list(sens.columns))
 glossary=r'''
\section{Glosario metodológico permanente}
\small
\begin{longtable}{p{2.7cm}p{4.5cm}p{2.2cm}p{5.2cm}}\toprule Métrica & Definición/fórmula & Rango y lectura & Uso y advertencia\\\midrule\endhead
ARI & Acuerdo entre todos los pares de observaciones, corregido por azar: $(RI-E[RI])/(\max(RI)-E[RI])$. & 1 idéntico; cerca de 0 acuerdo esperable por azar; puede ser negativo. & Particiones completas; global, no identifica qué cluster cambia y puede estar dominado por grupos grandes.\\
Jaccard & $|A\cap B|/|A\cup B|$. & 0--1; alto indica mayor solapamiento. & Empareja clusters entre escenarios; no es estabilidad individual ni cohesión geométrica.\\
Estabilidad de membresía & $s_i=\frac1{5}\sum_k I[z_i^{(k)}=m_k(z_i)]$, donde $m_k$ es el cluster alternativo de máximo Jaccard. & 0--1; sensible 0--.49, estable .50--.79, núcleo robusto .80--1. & Cinco especificaciones, peso .2 cada una. No es persistencia nativa HDBSCAN.\\
Probabilidad HDBSCAN & Fuerza de pertenencia estimada por HDBSCAN respecto de la estructura de densidad. & 0--1; alta=membresía más fuerte. & No es probabilidad causal ni estabilidad entre modelos.\\
Persistencia HDBSCAN & Estabilidad de un cluster a través de niveles de densidad del árbol condensado. & No comparable directamente con $s_i$. & Sólo se informa cuando proviene de \texttt{cluster\_persistence\_}; no sustituye Jaccard.\\
Ruido & Etiqueta $-1$ para puntos no asignados a clusters bajo una especificación. & 0--100\%. & Depende de escala y parámetros; no significa irrelevancia.\\
Cluster mayor & $100\max_c n_c/N$. & 0--100\%. & Diagnóstico de dominancia, no error automático.\\
Densidad & $n/$área convexa en km$^2$. & $\ge0$; alta=más puntos por área. & Sensible a forma, borde y áreas casi nulas; no equivale a cohesión.\\
Prevalencia & $a/n$. & 0--1 o porcentaje. & Multilabel: columnas no suman 100\%.\\
Diferencia de prevalencias & $p_c-p_U$ (en tablas, puntos porcentuales). & $[-1,1]$. & Efecto absoluto descriptivo.\\
Lift / $\log_2$ lift & $p_c/p_U$; $\log_2(p_c/p_U)$. & Lift $>0$; log2=0 igualdad, $>0$ sobre-, $<0$ subrepresentación. & No implica causalidad; inestable con base rara.\\
Odds ratio e IC95 & $ad/(bc)$; IC con corrección Haldane--Anscombe de 0.5. & OR=1 sin asociación; IC que cruza 1 es compatible con nulo. & Comparación cluster/resto, no riesgo causal.\\
Fisher / BH & Prueba exacta 2x2; BH controla tasa esperada de falsos descubrimientos. & $p\in[0,1]$; filtro $p_{BH}\le.05$. & Significancia no sustituye tamaño de efecto.\\
Cosine similarity/distance & $s=(x\cdot y)/(\|x\|\|y\|)$; $d=1-s$. & En vectores no negativos, 0--1 para distancia. & Vector de 18 prevalencias; compara patrón, no volumen.\\
Jensen--Shannon divergence/distance & $JSD=\frac12 KL(P\|M)+\frac12 KL(Q\|M)$; distancia $\sqrt{JSD}$, base 2. & 0--1. & Distribuciones SCIAN a 3 dígitos normalizadas por cluster; se usa distancia de SciPy.\\
Distancia combinada & $d=.5d_{cos}+.5d_{JS}$. & 0--1; bajo=perfiles similares. & Pesos analíticos iguales; no usa geografía ni personal ocupado.\\
Centroide / medoide & Media de coordenadas / punto observado que minimiza suma de distancias. & Coordenadas métricas EPSG:32614. & Centroide puede no coincidir con un establecimiento; medoide sí.\\
KDE & Suma suavizada de kernels sobre puntos. & Intensidad relativa dependiente del ancho de banda. & Diagnóstico exploratorio; no define membresías.\\
Perturbación espacial & A cada coordenada se suma ruido independiente $N(0,25^2)$ m por eje y se reajusta el modelo. & 3 repeticiones, semilla 20260921. & Evalúa sensibilidad posicional local, no error geodésico completo.\\
\bottomrule\end{longtable}\normalsize'''
 report=rf'''\documentclass[10pt]{{article}}\usepackage[utf8]{{inputenc}}\usepackage[T1]{{fontenc}}\usepackage[spanish,es-nodecimaldot]{{babel}}\usepackage{{geometry,graphicx,booktabs,longtable,array,float,xcolor,hyperref}}\geometry{{margin=1.8cm}}\graphicspath{{{{../../../outputs/parte_2/14_segunda_pasada/figuras/}}{{../../../outputs/parte_2/13_figuras_finales/}}}}\hypersetup{{colorlinks=true,linkcolor=blue}}\title{{Parte 2: concentraciones territoriales y composición\\Reporte técnico ampliado y auditable}}\author{{Proyecto Cuenca del Alto Atoyac}}\date{{Septiembre de 2026}}\begin{{document}}\maketitle\begin{{abstract}}Segunda pasada documental sobre la solución espacial fija HDBSCAN. No se reabre la selección ni se altera una membresía. Se explicitan definiciones, parámetros, fórmulas, diagnósticos desagregados, tablas completas y limitaciones. La detección usa 4,365 establecimientos y la interpretación 4,010 dentro de cuenca.\end{{abstract}}\tableofcontents
\section{{Hallazgo de auditoría y criterio de no modificación}}El campo histórico \texttt{{ari\_top5\_mismo\_metodo}} es la \emph{{media de las cinco particiones del mismo método con mayor ARI}}, no una vecindad definida en el espacio de parámetros. Se conserva el valor histórico para trazabilidad, pero se corrige el lenguaje. La métrica llamada antes ``persistencia territorial'' es una fracción de acuerdo individual no ponderada entre cinco especificaciones, después de emparejar clusters por máximo Jaccard; no es cohesión ni \texttt{{cluster\_persistence\_}} de HDBSCAN. Ningún resultado se cambió silenciosamente.
\section{{Diseño metodológico paso a paso}}\subsection{{Preparación espacial}}Coordenadas originales EPSG:4326, validación de valores y llaves únicas, reproyección a UTM 14N (EPSG:32614; unidades metros). Se detecta sobre 4,365 unidades municipales y se interpreta sobre 4,010 interiores; las 355 externas reducen corte artificial en el borde.
\subsection{{Diagnósticos preliminares}}Distancias $k$-NN diagnosticaron escalas locales; KDE representó intensidad suavizada sin membresías; hexágonos de 250 m resumieron ocupación y heterogeneidad. Son diagnósticos, no criterios productivos.
\subsection{{Grillas completas}}DBSCAN: $\epsilon\in\{{250,400,600,800,1200,1600\}}$ m y \texttt{{min\_samples}} $\in\{{5,10,15,25\}}$ (24). HDBSCAN: \texttt{{min\_cluster\_size}} $\in\{{10,20,30,50,75\}}$, \texttt{{min\_samples}} $\in\{{5,10,20\}}$, método EOM/leaf (30). OPTICS: \texttt{{min\_samples}} 10,20,30; $\xi=.05$; fracción mínima .01 (3). Total: 57.
\subsection{{Evaluación y referencia}}Se examinan número de clusters, ruido, porcentaje del cluster mayor, continuidad, probabilidad HDBSCAN, ARI entre particiones y ARI bajo perturbación. La referencia fija es \texttt{{min\_cluster\_size=10}}, \texttt{{min\_samples=20}}, EOM: {int(p.n_clusters)} clusters municipales, {p.pct_ruido:.1f}\% ruido y {p.pct_cluster_mayor:.1f}\% en el mayor. Es una solución operativa razonable, no la única verdad territorial.
{img('01_robustez_ari_documentada')}
\section{{ARI: definición, comparaciones y sensibilidad a grupos grandes}}ARI compara particiones completas mediante pares de observaciones y corrige acuerdo por azar. ARI=1 indica identidad; cerca de 0, acuerdo equivalente al azar; valores bajos o negativos, desacuerdo. La comparación histórica es la media de las cinco particiones HDBSCAN con mayor ARI frente a la principal. La perturbación suma ruido gaussiano independiente de desviación 25 m a cada eje, reajusta HDBSCAN completo tres veces y promedia; semilla maestra 20260921. Para ``sin ruido'' se restringe a observaciones no ruido en ambas particiones. Para ``sin mega'' se excluyen las observaciones cuyo cluster principal es 20. {ari_t} El descenso sin el mega-cluster confirma contribución de las categorías grandes, pero la estabilidad residual continúa alta en promedio; los mínimos completos están en \texttt{{resumen\_ari\_variantes.csv}}.
\section{{Estabilidad de membresía entre especificaciones}}Para cada cluster principal y cada una de cinco alternativas (DBSCAN de referencia y cuatro HDBSCAN de sensibilidad), se elige el cluster alternativo de Jaccard máximo. Para cada punto, $s_i$ es la fracción de alternativas donde permanece en ese emparejamiento; cada escenario pesa 0.2. Ruido se compara con ruido. Clases: sensible 0--.49; estable .50--.79; núcleo robusto .80--1. No es cohesión interna, densidad, probabilidad HDBSCAN ni persistencia nativa. {img('02_estabilidad_membresia')} {comp_t}
\section{{Mega-cluster 20 y 18 subnúcleos exploratorios}}El diagnóstico interno usa sólo coordenadas con HDBSCAN \texttt{{min\_cluster\_size=30}}, \texttt{{min\_samples=10}}, método leaf. Leaf favorece ramas locales con tamaño suficiente y se usa para revelar heterogeneidad, no para reemplazar el cluster 20. El 44.5\% no asignado significa que esos puntos no pertenecen a una rama local suficientemente densa bajo esta especificación; siguen perteneciendo al cluster principal. {img('03_subnucleos_mega_etiquetados')}\subsection{{Geometría}}Área convexa y densidad son descriptivas; el medoide es un establecimiento observado y la distancia vecina se mide entre centroides. {sub_t}\subsection{{Perfilado económico posterior}}Las siguientes variables se agregan después del diagnóstico espacial y no generaron los subnúcleos. {subp_t}
\section{{Composición multilabel y diccionario analítico}}Los términos son cadenas disparadoras; las etiquetas canónicas son indicadores reproducibles derivados; las categorías agregadas reúnen reglas como SCIAN o señales temáticas. El heatmap principal conserva ocho variables centrales, interpretables y poco redundantes; el ampliado muestra las 18 variables útiles. Ninguno incluye miles de términos crudos. La trazabilidad completa está en \texttt{{diccionario\_variables\_analiticas.csv}}. {img('04_heatmap_compacto')} {img('05_heatmap_ampliado')}
\section{{Sobrerrepresentación}}Una señal está sobrerrepresentada cuando $p_c>p_U$. $lift=p_c/p_U$ y $\log_2(lift)=\log_2(p_c/p_U)$: cero significa igualdad; positivo, sobre-representación; negativo, subrepresentación. Se distingue \texttt{{NO\_EVALUABLE}} (base global cero), \texttt{{NO\_SOBRERREPRESENTADO}} (lift $\le1$), \texttt{{FILTRADO\_POR\_CRITERIO}} y \texttt{{SOBRERREPRESENTADO}}. El filtro exige conteo $\ge5$, prevalencia $\ge5\%$, lift $\ge1.25$ y $p_{{BH}}\le.05$. La tabla completa contiene conteo, prevalencias, diferencia en puntos porcentuales, lift, log2 lift, OR, IC95, Fisher y BH; \texttt{{top\_rasgos\_por\_cluster.csv}} aporta 3--5 rasgos por cluster cuando existen.
\section{{Lavanderías frente a manufactura}}El 80\% es un umbral descriptivo, no una frontera natural. En la referencia fija hay 12 concentraciones manufactureras y seis mixtas; ninguna predominantemente lavandería. {img('08_ranking_lavanderia')} {prof_t} \subsection{{Sensibilidad en seis escenarios}}{sens_t} La evidencia responde: las lavanderías no forman clusters interiores casi exclusivos; aparecen sobre todo en estructuras mixtas y coexisten con confección, acabado, maquila y señales textiles en proporciones variables. La conclusión permanece en los seis escenarios seleccionados. Esto no demuestra relación empresarial, productiva o hidráulica.
\section{{Tipología y espacio métrico}}El vector coseno contiene prevalencias (0--1) de las 18 etiquetas canónicas. Se usa distancia, $1-(x\cdot y)/(\|x\|\|y\|)$. Jensen--Shannon usa distribuciones SCIAN de 3 dígitos normalizadas por cluster y la distancia (raíz de la divergencia, base 2) implementada por SciPy. Personal ocupado aparece en el archivo de vectores histórico, pero no interviene en la distancia. La distancia final es $.5d_{{cos}}+.5d_{{JS}}$, sin normalización adicional porque ambas están en 0--1. {img('06_distancia_coseno_senales')} {img('06_distancia_jensen_shannon_scian3')} {img('06_distancia_combinada_50_50')} {img('07_dendrograma_perfiles')}\subsection{{Por qué son similares los pares principales}}{pair_t}
\section{{Explorador interactivo}}\texttt{{outputs/parte\_2/14\_segunda\_pasada/explorador\_interactivo\_clusters.html}} es autocontenido: selecciona y compara dos clusters, ordena señales, alterna conteo/porcentaje, filtra señales presentes y cambia entre etiquetas compactas/ampliadas; muestra $n$, municipio, localidad, SCIAN, rasgos sobrerrepresentados, estabilidad, probabilidad y borde.
\section{{Actividad dispersa, limitaciones y cierre}}Los 578 puntos interiores no asignados son una categoría dependiente de escala, no un cluster equivalente. DENUE puede omitir actividad informal; la coordenada no prueba precisión predial; SCIAN 812210 no separa lavandería comercial de industrial; las etiquetas pueden correlacionarse. Concentración y coexistencia no prueban vínculos empresariales, consumo, descarga ni impacto. La relación hidrológica pertenece a Parte 3.
{glossary}
\appendix\section{{Las 57 configuraciones exploradas}}{tab(allcfg,list(allcfg.columns),list(allcfg.columns),{c:lambda x:f'{x:.3f}' for c in ['pct_ruido','pct_cluster_mayor','ari_top5_mismo_metodo','ari_perturbacion_25m']})}
\section{{Diccionario de variables analíticas}}{tab(dic,list(dic.columns),list(dic.columns))}
\section{{Índice de resultados completos}}\begin{{itemize}}\item \texttt{{diagnostico\_ari\_variantes.csv}} y \texttt{{componentes\_estabilidad\_por\_cluster.csv}}.\item \texttt{{subnucleos\_mega\_cluster\_documentados.csv}}.\item \texttt{{sobrerrepresentacion\_completa.csv}} y \texttt{{top\_rasgos\_por\_cluster.csv}}.\item Tres matrices de distancia y \texttt{{explicacion\_pares\_similares.csv}}.\item \texttt{{registro\_documentacion\_figuras.csv}} responde las siete preguntas de cierre por figura.\end{{itemize}}\end{{document}}'''
 pres=rf'''\documentclass[aspectratio=169]{{beamer}}\usepackage[utf8]{{inputenc}}\usepackage[T1]{{fontenc}}\usepackage[spanish]{{babel}}\usepackage{{graphicx,booktabs}}\usetheme{{Madrid}}\graphicspath{{{{../../../outputs/parte_2/14_segunda_pasada/figuras/}}{{../../../outputs/parte_2/13_figuras_finales/}}}}\title{{Parte 2: concentraciones y composición}}\subtitle{{Cierre metodológico ampliado}}\date{{Septiembre de 2026}}\begin{{document}}\frame{{\titlepage}}
\begin{{frame}}{{Qué se mantuvo fijo}}HDBSCAN: tamaño mínimo 10, muestras mínimas 20, EOM. Las variables económicas se incorporan sólo después. La segunda pasada documenta y audita; no redefine membresías.\end{{frame}}
\begin{{frame}}{{Exploración espacial}}24 DBSCAN + 30 HDBSCAN + 3 OPTICS. Diagnósticos $k$-NN, KDE y hexágonos. Coordenadas UTM 14N en metros.\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[width=.92\paperwidth,height=.9\paperheight,keepaspectratio]{{01_robustez_ari_documentada.png}}\end{{frame}}
\begin{{frame}}{{Cómo leer ARI}}ARI compara particiones completas y corrige acuerdo por azar. 1=idénticas; cerca de 0=azar. Es global: no dice qué cluster cambió. El eje X usa las cinco particiones del mismo método con mayor ARI, no vecindad paramétrica.\end{{frame}}
\begin{{frame}}{{¿Domina el mega-cluster?}}Top-5: ARI global 0.937; sin ruido 0.992; sin mega 0.819. Perturbación 25 m: 0.926, 0.986 y 0.896. La estabilidad sigue alta, pero el agregado global sí recibe aporte de grupos grandes.\end{{frame}}
\begin{{frame}}{{ARI versus estabilidad individual}}ARI compara toda la partición. Jaccard solapa dos clusters. Estabilidad de membresía cuenta en cuántas de cinco especificaciones conserva cada punto su cluster emparejado. No es cohesión ni persistencia nativa HDBSCAN.\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[height=.9\paperheight]{{02_estabilidad_membresia.png}}\end{{frame}}
\begin{{frame}}{{Solución principal}}22 clusters municipales; 18 dentro de cuenca; 578 puntos interiores dispersos. El cluster 20 reúne 1,997 establecimientos. Es referencia operativa, no geografía única.\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[height=.9\paperheight]{{03_subnucleos_mega_etiquetados.png}}\end{{frame}}
\begin{{frame}}{{Mega-cluster: qué significa 44.5\% no asignado}}HDBSCAN leaf, tamaño mínimo 30 y muestras mínimas 10, sólo coordenadas. Dieciocho ramas locales. Los no asignados carecen de densidad local suficiente en esta exploración, pero permanecen en el cluster 20 principal.\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[height=.9\paperheight]{{04_heatmap_compacto.png}}\end{{frame}}
\begin{{frame}}{{Por qué esas columnas}}Ocho etiquetas centrales, interpretables y no excesivamente redundantes. Los términos crudos activan etiquetas canónicas; las reglas SCIAN forman categorías agregadas. El anexo y el HTML contienen las 18 señales útiles.\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[height=.88\paperheight]{{08_ranking_lavanderia.png}}\end{{frame}}
\begin{{frame}}{{Lavanderías y manufactura}}12 concentraciones manufactureras, seis mixtas y ninguna con $\ge80\%$ lavandería. El 80\% es descriptivo. El patrón se conserva en seis escenarios; coexistencia no implica vínculo empresarial o hídrico.\end{{frame}}
\begin{{frame}}{{Qué significa sobrerrepresentación}}$lift=p_c/p_U$; $\log_2(lift)=0$ igualdad, positivo sobre-, negativo subrepresentación. Ejemplo: lift 2 significa prevalencia doble. Sólo se destaca con $n\ge5$, prevalencia $\ge5\%$, lift $\ge1.25$ y BH $\le.05$.\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[height=.88\paperheight]{{06_distancia_coseno_senales.png}}\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[height=.88\paperheight]{{06_distancia_jensen_shannon_scian3.png}}\end{{frame}}
\begin{{frame}}{{Dos preguntas distintas}}Coseno compara el patrón de prevalencias multilabel. Jensen--Shannon compara la distribución SCIAN-3. La tipología usa distancia combinada 50/50; valores bajos significan perfiles parecidos.\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[height=.88\paperheight]{{06_distancia_combinada_50_50.png}}\end{{frame}}
\begin{{frame}}[plain]\centering\includegraphics[width=.90\paperwidth,height=.84\paperheight,keepaspectratio]{{07_dendrograma_perfiles.png}}\end{{frame}}
\begin{{frame}}{{Pares más próximos}}14--18 (0.029), 4--13 (0.042), 12--13 (0.045), 16--19 (0.055), 7--21 (0.055). El reporte enumera señales y SCIAN compartidos y las diferencias que aún los separan.\end{{frame}}
\begin{{frame}}{{Actividad dispersa}}578 establecimientos interiores. ``Ruido'' depende de escala y parámetros; no significa ausencia de actividad ni forma un cluster comparable.\end{{frame}}
\begin{{frame}}{{Entrega interactiva}}HTML autocontenido: selección y comparación de clusters, conteos/porcentajes, señales presentes, etiquetas compactas/ampliadas, SCIAN, sobre-representación, estabilidad, probabilidad y borde.\end{{frame}}
\begin{{frame}}{{Conclusiones}}La estructura combina un continuo metropolitano, concentraciones menores y actividad dispersa. La solución es estable, aunque el ARI global se beneficia del mega-cluster. Las lavanderías aparecen en estructuras mixtas, no casi exclusivas. Parte 3 estudiará hidrología sin retroalimentar el clustering.\end{{frame}}
\begin{{frame}}{{Límites}}DENUE no mide procesos ni descargas. Multilabel no es clasificación exclusiva. Distancia productiva no es distancia geográfica. Asociación espacial no prueba relación empresarial, hidráulica ni causal.\end{{frame}}\end{{document}}'''
 rd=D/"reporte"; pd_=D/"presentacion"; rd.mkdir(parents=True,exist_ok=True); pd_.mkdir(parents=True,exist_ok=True)
 (rd/"reporte_tecnico_parte_2.tex").write_text(report,encoding="utf-8"); (pd_/"presentacion_parte_2.tex").write_text(pres,encoding="utf-8")
 glossary_md='''# Glosario metodológico permanente — Parte 2\n\nLa versión normativa con fórmulas, rangos, usos y advertencias está incorporada en el reporte técnico ampliado. Este archivo remite además a `outputs/parte_2/14_segunda_pasada/metadatos_metodologicos.json`, las tablas CSV auditables y `registro_documentacion_figuras.csv`.\n\nDistinciones críticas: ARI es global; Jaccard compara dos conjuntos; estabilidad de membresía es un acuerdo individual no ponderado entre cinco especificaciones; probabilidad HDBSCAN es fuerza de pertenencia; persistencia nativa HDBSCAN pertenece al árbol de densidad; densidad es puntos por área y no cohesión.\n'''
 (D/"metodologia"/"glosario_metodologico_parte2.md").write_text(glossary_md,encoding="utf-8")
 print("Documentos LaTeX ampliados generados")
if __name__=="__main__": main()
